# Jekyll configuration

name: WindWolf's Trace
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
url: "https://kirayamato4.github.io/"
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ""

author: kirayamato4
copyright: 2021-2020

# Handling Reading
exclude: ['README.md', 'LICENSE', '.git' ]

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: kirayamato4
comments: false

permalink: /:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

# Conversion
markdown: kramdown
highlighter: rouge
#lsi                 : false
#excerpt_separator   : "\n\n"
#incremental         : false



# Serving
detach              : false
port                : 8080
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Markdown Processors
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
  syntax_highlighter: rouge